Feat/visible config
maelgangloff/scolengo-api pull request #41
Opened 2024-03-18 22:30 UTC by NonozgYtb

# Description de la demande de fusion

Création d'un objet de configuration utile notamment pour l'utilisation de ce package avec une intégration personnalisé (ex : intégration custom avec un package OIDC-like)

## Type de changement

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] Mon code ne met pas en danger les données personnelles des utilisateurs
- [x] Les noms des commits suivent la convention [Conventional Commits](https://www.conventionalcommits.org/fr/v1.0.0/)
- [x] J'ai vérifié l'entièreté du code avant de le soumettre
- [x] J'ai mis à jour la documentation en lien avec mes commits
- [x] Mon code ne génère pas d'erreurs

### Note
Avant de fusionner cette PR, elle devra recevoir l'approbation d'au moins une des personnes suivantes :
- [@maelgangloff](https://github.com/maelgangloff)

2024-03-18 22:33 UTC, vinceh121 requested changes

2024-03-18 22:33 UTC, vinceh121 commented on src/index.ts
> +const REDIRECTURI = 'skoapp-prod://sign-in-callback'
```suggestion
const REDIRECT_URI = 'skoapp-prod://sign-in-callback'
```

2024-03-18 22:35 UTC, NonozgYtb commented on src/index.ts
> +const REDIRECTURI = 'skoapp-prod://sign-in-callback'
Bonne idée, j'en fais un commit à part entière pour inclure la doc 😉 !

2024-03-19 18:59 UTC, maelgangloff approved these changes
Cet ajout permet de rendre plus facile l'utilisation de la librairie en exposant les constantes nécessaires à l'authentification via *OpenID Connect*.

Merci @NonozgYtb :tada:

2024-03-19 19:25 UTC, vinceh121 commented
Peut-être exporter les constantes directement hors la classe, pour pouvoir importer comme ça

```typescript
import {Skolengo, BASE_URL} from 'scolengo-api'
```

2024-03-19 19:34 UTC, vinceh121 approved these changes

2024-03-19 19:38 UTC, merged